FROM apache/airflow:2.10.2

WORKDIR /opt/airflow

USER airflow


RUN mkdir -p /opt/airflow/src
COPY ./src /opt/airflow/src

RUN mkdir -p /opt/airflow/configs
COPY ./configs /opt/airflow/configs

COPY requirements.txt /opt/airflow/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

USER root

RUN chown -R 1000:0 /opt/airflow

ENV PYTHONPATH="${PYTHONPATH}:/opt/airflow"

USER airflow

COPY logger_config.json .
