services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_EXPOSED_PORT:-5432}:5432'
    networks:
      - webnet

  fastapi:
    build: .
    volumes:
      - .:/app
    networks:
      - webnet
    depends_on:
      - postgres

  fastapi1:
    extends:
      service: fastapi
    ports:
      - 8000
    environment:
      - SERVER_ID=SERVER-1

  fastapi2:
    extends:
      service: fastapi
    ports:
      - 8000
    environment:
      - SERVER_ID=SERVER-2

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fastapi1
      - fastapi2
    networks:
      - webnet

networks:
  webnet:

volumes:
  database:
