version: "3.9"

services:
  fastapi1:
    build: .
    ports:
      - "8800:8000"
    volumes:
      - .:/app
      - db_data:/app/db_data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - SERVER_ID=SERVER-2
    networks:
      - webnet

  fastapi2:
    build: .
    ports:
      - "8880:8000"
    volumes:
      - .:/app
      - db_data:/app/db_data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - SERVER_ID=SERVER-2
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fastapi1
      - fastapi2
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
