version: "3.9"

services:
  fastapi1:
    build: .
    ports:
      - "8800:8000"
    volumes:
      - .:/app
      - ./src/db_data_1:/app/src/db_data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - SERVER_ID=SERVER-1
    networks:
      - webnet
    entrypoint: ["/bin/sh", "-c", "./src/migrate_and_seed_db.py && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"]

  fastapi2:
    build: .
    ports:
      - "8880:8000"
    volumes:
      - .:/app
      - ./src/db_data_2:/app/src/db_data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - SERVER_ID=SERVER-2
    networks:
      - webnet
    entrypoint: ["/bin/sh", "-c", "./src/migrate_and_seed_db.py && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fastapi1
      - fastapi2
    networks:
      - webnet

networks:
  webnet:
