[tool.pytest_env]
APP_ENV = "testing"

[tool.flake8]
exclude = [
    "**/__pycache__/", 
    "venv",
    "database",
]

[tool.yapf]
based_on_style = "facebook"
column_limit = 79

[tool.isort]
skip = [
    "venv",
    "database",
]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true