name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Set ssh key 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Deploy to Server
        if: ${{ success() }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd apps
            cd pyforge-python-school-3
            git pull
            docker compose build
          EOF
