name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env.testing
        run: cp .env.testing.example .env.testing

      - name: Build Docker image
        run: docker build --build-arg APP_ENV=testing -t fastapi-app .

      # - name: Run tests
      #   run: docker run --rm fastapi-app pytest

      - name: Run flake8 on src directory
        run: docker run --rm fastapi-app pflake8
