name: CI Pipeline

on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and start Docker Compose services
      run: docker-compose up -d --build

    - name: Wait for FastAPI service to be ready
      run: |
        until curl -s http://localhost:8800 | grep "SERVER-1"; do
          echo "Waiting for service to be ready..."
          sleep 10
        done

    - name: Run Tests
      run: docker-compose exec fastapi1 pytest /app/tests

    - name: Run Static Analysis with Flake8
      run: docker-compose exec fastapi1 flake8 /app/src

    - name: Shutdown Docker Compose services
      run: docker-compose down
