name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Run tests
        run: docker run --rm fastapi-app pytest

      - name: Run flake8 on src directory
        run: docker run --rm fastapi-app "flake8 src"
