name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Inject sensitive values into .env
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

      - name: Build and run services
        run: |
          docker compose up --build -d

      - name: Run pytest
        run: |
          docker compose exec fastapi pytest

      - name: Run flake8
        run: |
          docker compose exec fastapi flake8 ./src
